import { PrismaClient } from "../generated/prisma";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const MAMMALS = [
  { commonName: "Aardvark", category: "Mammal" },
  { commonName: "Aardwolf", category: "Mammal" },
  { commonName: "African Buffalo", category: "Mammal" },
  { commonName: "African Wildcat", category: "Mammal" },
  { commonName: "African Wild Dog", category: "Mammal" },
  { commonName: "African Elephant", category: "Mammal" },
  { commonName: "Banded Mongoose", category: "Mammal" },
  { commonName: "Black-backed Jackal", category: "Mammal" },
  { commonName: "Black Rhinoceros", category: "Mammal" },
  { commonName: "Blue Wildebeest", category: "Mammal" },
  { commonName: "Bushbuck", category: "Mammal" },
  { commonName: "Bushveld Elephant Shrew", category: "Mammal" },
  { commonName: "Burchells Zebra", category: "Mammal" },
  { commonName: "Caracal", category: "Mammal" },
  { commonName: "Chacma Baboon", category: "Mammal" },
  { commonName: "Cheetah", category: "Mammal" },
  { commonName: "Civet", category: "Mammal" },
  { commonName: "Common Duiker", category: "Mammal" },
  { commonName: "Dwarf Mongoose", category: "Mammal" },
  { commonName: "Egyptian Slit-faced Bat", category: "Mammal" },
  { commonName: "Giraffe", category: "Mammal" },
  { commonName: "Greater Kudu", category: "Mammal" },
  { commonName: "Hippopotamus", category: "Mammal" },
  { commonName: "Honey Badger", category: "Mammal" },
  { commonName: "House Mouse", category: "Mammal" },
  { commonName: "Impala", category: "Mammal" },
  { commonName: "Klipspringer", category: "Mammal" },
  { commonName: "Large Spotted Genet", category: "Mammal" },
  { commonName: "Leopard", category: "Mammal" },
  { commonName: "Lesser Bushbaby", category: "Mammal" },
  { commonName: "Lesser Savannah Dormouse", category: "Mammal" },
  { commonName: "Lion", category: "Mammal" },
  { commonName: "Nile Crocodile", category: "Reptile" },
  { commonName: "Nyala", category: "Mammal" },
  { commonName: "Pangolin", category: "Mammal" },
  { commonName: "Porcupine", category: "Mammal" },
  { commonName: "Pouched Mouse", category: "Mammal" },
  { commonName: "Reddish-grey Musk Shrew", category: "Mammal" },
  { commonName: "Reedbuck", category: "Mammal" },
  { commonName: "Red Veldrat", category: "Mammal" },
  { commonName: "Scrub Hare", category: "Mammal" },
  { commonName: "Serval", category: "Mammal" },
  { commonName: "Sharpes Greysbok", category: "Mammal" },
  { commonName: "Single-striped Mouse", category: "Mammal" },
  { commonName: "Side-striped Jackal", category: "Mammal" },
  { commonName: "Slender Mongoose", category: "Mammal" },
  { commonName: "Small Spotted Genet", category: "Mammal" },
  { commonName: "Spring Hare", category: "Mammal" },
  { commonName: "Spotted Hyena", category: "Mammal" },
  { commonName: "Steenbok", category: "Mammal" },
  { commonName: "Striped Polecat", category: "Mammal" },
  { commonName: "Tree Mouse", category: "Mammal" },
  { commonName: "Tree Squirrel", category: "Mammal" },
  { commonName: "Vervet Monkey", category: "Mammal" },
  { commonName: "Wahlbergs Epauletted Fruit Bat", category: "Mammal" },
  { commonName: "Warthog", category: "Mammal" },
  { commonName: "Waterbuck", category: "Mammal" },
  { commonName: "White-tailed Mongoose", category: "Mammal" },
  { commonName: "White Rhinoceros", category: "Mammal" },
];

const BIRDS = [
  { commonName: "Bar-Throated Apalis", family: "Apalis" },
  { commonName: "Yellow-breasted Apalis", family: "Apalis" },
  { commonName: "Arrow-marked Babbler", family: "Babbler" },
  { commonName: "Blackcollared Barbet", family: "Barbet" },
  { commonName: "Crested Barbet", family: "Barbet" },
  { commonName: "Acacia Pied Barbet", family: "Barbet" },
  { commonName: "Bateleur", family: "Bateleur" },
  { commonName: "Chinspot Batis", family: "Batis" },
  { commonName: "European Bee-eater", family: "Bee-eater" },
  { commonName: "Little Bee-eater", family: "Bee-eater" },
  { commonName: "Southern Carmine Bee-eater", family: "Bee-eater" },
  { commonName: "White-fronted Bee-eater", family: "Bee-eater" },
  { commonName: "Southern Boubou", family: "Boubou" },
  { commonName: "Brubru", family: "Brubru" },
  { commonName: "Terrestrial Brownbul", family: "Bulbul" },
  { commonName: "Dark-capped Bulbul", family: "Bulbul" },
  { commonName: "Sombre Greenbul", family: "Bulbul" },
  { commonName: "Kori Bustard", family: "Bustard" },
  { commonName: "Red-crested Korhaan", family: "Bustard" },
  { commonName: "Golden-breasted Bunting", family: "Bunting" },
  { commonName: "Cinnamon-breasted Bunting", family: "Bunting" },
  { commonName: "Small Buttonquail", family: "Buttonquail" },
  { commonName: "Lizard Buzzard", family: "Buzzard" },
  { commonName: "Steppe Buzzard", family: "Buzzard" },
  { commonName: "Brimstone Canary", family: "Canary" },
  { commonName: "Yellow-fronted Canary", family: "Canary" },
  { commonName: "Familiar Chat", family: "Chat" },
  { commonName: "Zitting Cisticola", family: "Cisticola" },
  { commonName: "Levaillant's Cisticola", family: "Cisticola" },
  { commonName: "Rattling Cisticola", family: "Cisticola" },
  { commonName: "Red-knobbed Coot", family: "Coot" },
  { commonName: "Reed Cormorant", family: "Cormorant" },
  { commonName: "White-breasted Cormorant", family: "Cormorant" },
  { commonName: "Burchell's Coucal", family: "Coucal" },
  { commonName: "Bronze-winged Courser", family: "Courser" },
  { commonName: "Temminck's Courser", family: "Courser" },
  { commonName: "Black Crake", family: "Crake" },
  { commonName: "Longbilled Crombec", family: "Crombec" },
  { commonName: "African Cuckoo", family: "Cuckoo" },
  { commonName: "Black Cuckoo", family: "Cuckoo" },
  { commonName: "Diederik Cuckoo", family: "Cuckoo" },
  { commonName: "Common Cuckoo", family: "Cuckoo" },
  { commonName: "Jacobin Cuckoo", family: "Cuckoo" },
  { commonName: "Klaas's Cuckoo", family: "Cuckoo" },
  { commonName: "Redchested Cuckoo", family: "Cuckoo" },
  { commonName: "Levaillant's Cuckoo", family: "Cuckoo" },
  { commonName: "Fork-tailed Drongo", family: "Drongo" },
  { commonName: "African Fish Eagle", family: "Eagle" },
  { commonName: "Martial Eagle", family: "Eagle" },
  { commonName: "Tawny Eagle", family: "Eagle" },
  { commonName: "Wahlberg's Eagle", family: "Eagle" },
  { commonName: "Brown Snake Eagle", family: "Eagle" },
  { commonName: "Black-chested Snake Eagle", family: "Eagle" },
  { commonName: "African Hawk-Eagle", family: "Eagle" },
  { commonName: "Cattle Egret", family: "Egret" },
  { commonName: "Great Egret", family: "Egret" },
  { commonName: "Yellow-billed Egret", family: "Egret" },
  { commonName: "Red-billed Firefinch", family: "Firefinch" },
  { commonName: "Southern Grey-headed Sparrow", family: "Sparrow" },
  { commonName: "House Sparrow", family: "Sparrow" },
  { commonName: "Little Sparrowhawk", family: "Sparrowhawk" },
  { commonName: "Ovambo Sparrowhawk", family: "Sparrowhawk" },
  { commonName: "Rufous-chested Sparrowhawk", family: "Sparrowhawk" },
  { commonName: "African Spoonbill", family: "Spoonbill" },
  { commonName: "Burchell's Starling", family: "Starling" },
  { commonName: "Greater Blue-eared Starling", family: "Starling" },
  { commonName: "Violet-backed Starling", family: "Starling" },
  { commonName: "Wattled Starling", family: "Starling" },
  { commonName: "Cape Glossy Starling", family: "Starling" },
  { commonName: "African Openbill Stork", family: "Stork" },
  { commonName: "Black Stork", family: "Stork" },
  { commonName: "Marabou Stork", family: "Stork" },
  { commonName: "Saddle-billed Stork", family: "Stork" },
  { commonName: "White Stork", family: "Stork" },
  { commonName: "Woolly-necked Stork", family: "Stork" },
  { commonName: "Yellow-billed Stork", family: "Stork" },
  { commonName: "Marko Sunbird", family: "Sunbird" },
  { commonName: "Scarlet-chested Sunbird", family: "Sunbird" },
  { commonName: "White-bellied Sunbird", family: "Sunbird" },
  { commonName: "Barn Swallow", family: "Swallow" },
  { commonName: "Greater Striped Swallow", family: "Swallow" },
  { commonName: "Lesser Striped Swallow", family: "Swallow" },
  { commonName: "Red-breasted Swallow", family: "Swallow" },
  { commonName: "White-throated Swallow", family: "Swallow" },
  { commonName: "Common Swift", family: "Swift" },
  { commonName: "Black-crowned Tchagra", family: "Tchagra" },
  { commonName: "Brown-crowned Tchagra", family: "Tchagra" },
  { commonName: "Spotted Thick-knee", family: "Thick-knee" },
  { commonName: "Water Thick-knee", family: "Thick-knee" },
  { commonName: "Groundscraper Thrush", family: "Thrush" },
  { commonName: "Southern Black Tit", family: "Tit" },
  { commonName: "Cape Vulture", family: "Vulture" },
  { commonName: "Hooded Vulture", family: "Vulture" },
  { commonName: "Lappet-faced Vulture", family: "Vulture" },
  { commonName: "White-backed Vulture", family: "Vulture" },
  { commonName: "White-headed Vulture", family: "Vulture" },
  { commonName: "African Pied Wagtail", family: "Wagtail" },
  { commonName: "Grey-backed Camaroptera", family: "Warbler" },
  { commonName: "Green-backed Camaroptera", family: "Warbler" },
  { commonName: "Olive Tree Warbler", family: "Warbler" },
  { commonName: "Stierling's Wren Warbler", family: "Warbler" },
  { commonName: "Willow Warbler", family: "Warbler" },
  { commonName: "Blue Waxbill", family: "Waxbill" },
  { commonName: "Common Waxbill", family: "Waxbill" },
  { commonName: "Violet-eared Waxbill", family: "Waxbill" },
  { commonName: "Lesser Masked Weaver", family: "Weaver" },
  { commonName: "Southern Masked Weaver", family: "Weaver" },
  { commonName: "Red-billed Buffalo Weaver", family: "Weaver" },
  { commonName: "Red-headed Weaver", family: "Weaver" },
  { commonName: "Spectacled Weaver", family: "Weaver" },
  { commonName: "Village Weaver", family: "Weaver" },
  { commonName: "Cape White-eye", family: "White-eye" },
  { commonName: "Long-tailed Paradise-whydah", family: "Whydah" },
  { commonName: "Pin-tailed Whydah", family: "Whydah" },
  { commonName: "Shaft-tailed Whydah", family: "Whydah" },
  { commonName: "Green Wood-hoopoe", family: "Wood-hoopoe" },
  { commonName: "Common Scimitarbill", family: "Wood-hoopoe" },
  { commonName: "Bearded Woodpecker", family: "Woodpecker" },
  { commonName: "Bennett's Woodpecker", family: "Woodpecker" },
  { commonName: "Cardinal Woodpecker", family: "Woodpecker" },
  { commonName: "Golden-tailed Woodpecker", family: "Woodpecker" },
  { commonName: "Yellow-billed Oxpecker", family: "Oxpecker" },
  { commonName: "Red-billed Oxpecker", family: "Oxpecker" },
  { commonName: "Brown-headed Parrot", family: "Parrot" },
  { commonName: "African Green Pigeon", family: "Pigeon" },
  { commonName: "Buffy Pipit", family: "Pipit" },
  { commonName: "Bushveld Pipit", family: "Pipit" },
  { commonName: "African Pipit", family: "Pipit" },
  { commonName: "Three-banded Plover", family: "Plover" },
  { commonName: "Tawny-flanked Prinia", family: "Prinia" },
  { commonName: "Black-back Puffback", family: "Puffback" },
  { commonName: "Common Quail", family: "Quail" },
  { commonName: "Harlequin Quail", family: "Quail" },
  { commonName: "Red-billed Quelea", family: "Quelea" },
  { commonName: "Bearded Scrub-robin", family: "Robin" },
  { commonName: "White-browed Robin-chat", family: "Robin" },
  { commonName: "Red-capped Robin-chat", family: "Robin" },
  { commonName: "White-browed Scrub-chat", family: "Robin" },
  { commonName: "White-throated Robin-chat", family: "Robin" },
  { commonName: "European Roller", family: "Roller" },
  { commonName: "Lilac-breasted Roller", family: "Roller" },
  { commonName: "Purple Roller", family: "Roller" },
  { commonName: "Fiery-necked Nightjar", family: "Nightjar" },
  { commonName: "Spotted Eagle Owl", family: "Owl" },
  { commonName: "Southern White-faced Scops Owl", family: "Owl" },
  { commonName: "Double-banded Sandgrouse", family: "Sandgrouse" },
  { commonName: "Common Sandpiper", family: "Sandpiper" },
  { commonName: "Curlew Sandpiper", family: "Sandpiper" },
  { commonName: "Secretarybird", family: "Secretarybird" },
  { commonName: "Grey-headed Bush Shrike", family: "Shrike" },
  { commonName: "Lesser Grey Shrike", family: "Shrike" },
  { commonName: "Magpie Shrike", family: "Shrike" },
  { commonName: "Orange-breasted Bush Shrike", family: "Shrike" },
  { commonName: "Red-backed Shrike", family: "Shrike" },
  { commonName: "Southern White-crowned Shrike", family: "Shrike" },
  { commonName: "Greater Painted Snipe", family: "Snipe" },
  { commonName: "Southern Yellow-billed Hornbill", family: "Hornbill" },
  { commonName: "Red-billed Hornbill", family: "Hornbill" },
  { commonName: "Southern Ground Hornbill", family: "Hornbill" },
  { commonName: "Grey Hornbill", family: "Hornbill" },
  { commonName: "Grey Heron", family: "Heron" },
  { commonName: "Goliath Heron", family: "Heron" },
  { commonName: "Green-backed Heron", family: "Heron" },
  { commonName: "Black-headed Heron", family: "Heron" },
  { commonName: "Hamerkop", family: "Hamerkop" },
  { commonName: "Helmeted Guineafowl", family: "Guineafowl" },
  { commonName: "Crested Francolin", family: "Francolin" },
  { commonName: "Swainson's Spurfowl", family: "Francolin" },
  { commonName: "Natal Spurfowl", family: "Francolin" },
  { commonName: "Grey Go-away-bird", family: "Turaco" },
  { commonName: "Purple-crested Turaco", family: "Turaco" },
  { commonName: "Red-faced Mousebird", family: "Mousebird" },
  { commonName: "Speckled Mousebird", family: "Mousebird" },
  { commonName: "Green-winged Pytilia", family: "Pytilia" },
  { commonName: "Woodland Kingfisher", family: "Kingfisher" },
  { commonName: "Brown-hooded Kingfisher", family: "Kingfisher" },
  { commonName: "Pied Kingfisher", family: "Kingfisher" },
  { commonName: "Malachite Kingfisher", family: "Kingfisher" },
  { commonName: "Giant Kingfisher", family: "Kingfisher" },
  { commonName: "African Jacana", family: "Jacana" },
  { commonName: "Blacksmith Lapwing", family: "Lapwing" },
  { commonName: "Crowned Lapwing", family: "Lapwing" },
  { commonName: "African Wattled Lapwing", family: "Lapwing" },
].map((b) => ({ ...b, category: "Bird" }));

const REPTILES = [
  { commonName: "Monitor Lizard", category: "Reptile" },
  { commonName: "Python", category: "Reptile" },
  { commonName: "Flap-necked Chameleon", category: "Reptile" },
  { commonName: "Leopard Tortoise", category: "Reptile" },
];

const ALL_SPECIES = [...MAMMALS, ...BIRDS, ...REPTILES];

async function main() {
  const lodges = [
    {
      name: "Nzumba Camp",
      brand: "Klaserie Camps",
      latitude: -24.1925,
      longitude: 31.0742,
    },
    {
      name: "Last Word Kitara",
      brand: "The Last Word",
      latitude: -24.2048,
      longitude: 31.0831,
    },
    {
      name: "Dundee Camp",
      brand: "Klaserie Camps",
      latitude: -24.1812,
      longitude: 31.0654,
    },
  ];

  const createdLodges = [];
  for (const lodgeData of lodges) {
    const lodge = await prisma.lodge.upsert({
      where: { name: lodgeData.name },
      update: {
        brand: lodgeData.brand,
        latitude: lodgeData.latitude,
        longitude: lodgeData.longitude,
      },
      create: lodgeData,
    });
    createdLodges.push(lodge);
    console.log(`Lodge created: ${lodge.name} (${lodge.latitude}, ${lodge.longitude})`);
  }

  const defaultLodge = createdLodges[0]!;

  const hashedPassword = await bcrypt.hash("admin123", 12);
  await prisma.user.upsert({
    where: { email: "admin@safari-track.local" },
    update: { role: "ADMIN", hashedPassword, lodgeId: defaultLodge.id },
    create: {
      name: "Admin",
      email: "admin@safari-track.local",
      hashedPassword,
      role: "ADMIN",
      lodgeId: defaultLodge.id,
    },
  });

  console.log("Admin user created: admin@safari-track.local / admin123");

  let created = 0;
  for (const species of ALL_SPECIES) {
    const family = "family" in species ? (species.family as string) : null;
    await prisma.species.upsert({
      where: { commonName: species.commonName },
      update: { family },
      create: {
        commonName: species.commonName,
        category: species.category,
        family,
      },
    });
    created++;
  }

  console.log(`${created} species seeded`);
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
